import type { Metadata } from "next";
import { NextAuthProvider } from "./providers";
import ClientLayout from "@/components/ClientLayout";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <ClientLayout>{children}</ClientLayout>
        </NextAuthProvider>
      </body>
    </html>
  );
}