import type { Metadata } from "next";
import { NextAuthProvider } from "./providers";
import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <div className="flex flex-col min-h-screen bg-gray-50 dark:bg-zinc-900">
            <Navbar />
            <main className="flex-1">
              {children}
            </main>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
